/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as AuthorizedRouteImport } from './routes/_authorized'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorizedTablesRouteImport } from './routes/_authorized/tables'
import { Route as AuthorizedProfileRouteImport } from './routes/_authorized/profile'
import { Route as AuthorizedDashboardRouteImport } from './routes/_authorized/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedRoute = AuthorizedRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedTablesRoute = AuthorizedTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AuthorizedRoute,
} as any)
const AuthorizedProfileRoute = AuthorizedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthorizedRoute,
} as any)
const AuthorizedDashboardRoute = AuthorizedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthorizedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthorizedDashboardRoute
  '/profile': typeof AuthorizedProfileRoute
  '/tables': typeof AuthorizedTablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthorizedDashboardRoute
  '/profile': typeof AuthorizedProfileRoute
  '/tables': typeof AuthorizedTablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authorized': typeof AuthorizedRouteWithChildren
  '/documentation': typeof DocumentationRoute
  '/login': typeof LoginRoute
  '/_authorized/dashboard': typeof AuthorizedDashboardRoute
  '/_authorized/profile': typeof AuthorizedProfileRoute
  '/_authorized/tables': typeof AuthorizedTablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/documentation' | '/login' | '/dashboard' | '/profile' | '/tables'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/documentation' | '/login' | '/dashboard' | '/profile' | '/tables'
  id:
    | '__root__'
    | '/'
    | '/_authorized'
    | '/documentation'
    | '/login'
    | '/_authorized/dashboard'
    | '/_authorized/profile'
    | '/_authorized/tables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizedRoute: typeof AuthorizedRouteWithChildren
  DocumentationRoute: typeof DocumentationRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized': {
      id: '/_authorized'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized/tables': {
      id: '/_authorized/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof AuthorizedTablesRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_authorized/profile': {
      id: '/_authorized/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthorizedProfileRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_authorized/dashboard': {
      id: '/_authorized/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthorizedDashboardRouteImport
      parentRoute: typeof AuthorizedRoute
    }
  }
}

interface AuthorizedRouteChildren {
  AuthorizedDashboardRoute: typeof AuthorizedDashboardRoute
  AuthorizedProfileRoute: typeof AuthorizedProfileRoute
  AuthorizedTablesRoute: typeof AuthorizedTablesRoute
}

const AuthorizedRouteChildren: AuthorizedRouteChildren = {
  AuthorizedDashboardRoute: AuthorizedDashboardRoute,
  AuthorizedProfileRoute: AuthorizedProfileRoute,
  AuthorizedTablesRoute: AuthorizedTablesRoute,
}

const AuthorizedRouteWithChildren = AuthorizedRoute._addFileChildren(
  AuthorizedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizedRoute: AuthorizedRouteWithChildren,
  DocumentationRoute: DocumentationRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
